from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean
from datetime import datetime
from .database import Base

class StrategyModel(Base):
    __tablename__ = "strategies"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, index=True)
    description = Column(String)
    content = Column(Text)  # Detailed markdown content of the strategy
    is_active = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class AnalysisModel(Base):
    __tablename__ = "analysis_history"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    symbol = Column(String, index=True)
    timeframe = Column(String)
    signal = Column(String)  # BULLISH, BEARISH, NEUTRAL, NEUTRAL_WAITING
    confidence = Column(Integer)  # 0 to 100
    reasoning = Column(Text)  # Full explanation generated by the LLM
    invalidation = Column(Text)  # SL and setup invalidation details
    risk_notes = Column(Text)  # Risk warning / reward notes
    chart_data = Column(Text, nullable=True)  # JSON string of market data at analysis time

class PreferenceModel(Base):
    __tablename__ = "preferences"

    id = Column(Integer, primary_key=True, index=True)
    key = Column(String, unique=True, index=True)
    value = Column(String)
